version: '3'
services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOCKERPORT: ${DOCKERPORT}
      # For use with LetsEncrypt, see README.md
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      # For use with LetsEncrypt, see README.md
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      # For use with LetsEncrypt, see README.md
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - ${DOCKERPORT}:80
    links:
      - database
    volumes:
      - "./do-not-commit:/do-not-commit"
      - "uploaded-files:/var/www/html/images"
      - "./docker-resources:/docker-resources"
  database:
    image: mariadb
    restart: always
    volumes:
      - "mysql:/var/lib/mysql"
      - "./do-not-commit:/do-not-commit"
      - "./docker-resources:/docker-resources"
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  uploaded-files:
  mysql:
